project_name: newrelic-azure-functions

env:
  - GO111MODULE=on

before:
  hooks:
    - make clean
    - go mod download

# This is a hack to NOT build binaries...
builds:
  -
    id: "default"
    goos:
      - linux
    goarch:
      - amd64
    ignore:
      - goos: linux
        goarch: amd64

release:
  # Mark as a pre-release for now
  prerelease: true
  name_template: "{{.ProjectName}} v{{.Version}}"

# Already using git-chglog
changelog:
  skip: true
